name: "JMH Benchmark Action"
description: "Runs JMH benchmarks on PR and base branch, then compares results"
author: "Your Name"

inputs:
  java-version:
    description: "Java version to use"
    required: true
    default: "11"
  base-ref:
    description: "Reference for the base branch (e.g., 'main', 'master', commit SHA)"
    required: true
  benchmark-command:
    description: "Command to execute the benchmark"
    required: true
  benchmark-file:
    description: "Path to the benchmark results file"
    required: true
    default: "benchmark.json"

runs:
  using: "composite"
  steps:
    - name: Check out PR branch
      uses: actions/checkout@v4
      with:
        path: pr
    - name: Check out base branch
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.base-ref }}
        path: base
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ inputs.java-version }}
    - name: Set up Groovy
      uses: wtfjoke/setup-groovy@v2
      with:
        groovy-version: '4.x'
    - name: Run benchmarks on base branch
      run: |
        cd base
        ${{ inputs.benchmark-command }}
      shell: bash
    - name: Run benchmarks on PR branch
      run: |
        cd pr
        ${{ inputs.benchmark-command }}
      shell: bash
    - name: Compare benchmark results with Groovy
      id: compare
      run: groovy -cp ${{ github.action_path }} ${{ github.action_path }}/compare.groovy
      shell: bash
    - name: Save PR number to file
      run: echo "${{ github.event.number }}" > pr_number.txt
      shell: bash
    - name: Upload comment as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-comment
        path: benchmark-comment.md
    - name: Upload PR number as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: pr-number
        path: pr_number.txt
